# inherit_from: ../.rubocop.yml

require:
- rubocop-i18n

AllCops:
  DisabledByDefault: true
  Exclude:
  - 'db/migrate/*'

# Style/StringLiterals:
#   EnforcedStyle: single_quotes
#   Enabled: true

Layout:
  Enabled: true
I18n/RailsI18n:
  Enabled: true
I18n/GetText:
  Enabled: false
# I18n/RailsI18n/DecorateStringFormattingUsingInterpolation:
#   Enabled: true
#   AutoCorrect: false
# I18n/RailsI18n/DecorateString:
#   Enabled: true
#   AutoCorrect: false
# I18n/GetText/DecorateFunctionMessage:
#   Enabled: true
#   AutoCorrect: false
# I18n/GetText/DecorateStringFormattingUsingPercent:
#   Enabled: true
#   AutoCorrect: false

# Style/Encoding:
#   Enabled: false

# Layout/LineLength:
#   Max: 99

Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true
