# docker-compose.yaml - compose five docker images to run zitat-service.de
# - mariadb with loaded test data
# - phpMySqlAdmin
# - ruby on rails web application zitat-service.de
# - Selenium with headless chrome with locale de and VNC server for system tests
# - maildev SMTP server for testing mails

services:
  db:
    container_name: quote_mariadb
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - .:/var/www
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: quote_development
      MARIADB_USER: quote_development
      MARIADB_PASSWORD: quote_development
    restart: unless-stopped
  mysqladmin:
    container_name: quote_mysqladmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8101:80"
    restart: unless-stopped
    depends_on:
      - db
  rails:
    container_name: quote_rails
    build:
      context: .
      dockerfile: rails.Dockerfile
    volumes:
      - .:/quote
    environment:
      QUOTE_DATABASE_PASSWORD: quote_development
    ports:
      - "8102:3000" # development environment
      - "8112:3100" # test environment, if running
    restart: unless-stopped
    depends_on:
      - db
      - chrome
  chrome:
    container_name: quote_chrome
    image: selenium/standalone-chrome
    ports:
      - "8104:5900" # VNC
      - "8105:7900" # noVNC http://localhost:8105/?autoconnect=1&resize=scale&password=secret
    volumes:
      - /dev/shm:/dev/shm
    shm_size: '2gb'
    restart: unless-stopped
  maildev:
    container_name: quote_maildev
    image: maildev/maildev
    ports:
      - "8106:1080"
    restart: unless-stopped
