# docker-compose.yaml - compose three docker images (mariadb with loaded test data, phpmysqladmin and Rails) to run zitat-service.de
#
version: '3'
services:
  db:
    container_name: quote_mariadb
    build:
      context: .
      dockerfile: db.Dockerfile
    image: mariadb
    volumes:
      - .:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quote_development
      MYSQL_USER: quote_development
      MYSQL_PASSWORD: quote_development
    ports:
      - "8100:3306"
    restart: always
  mysqladmin:
    container_name: quote_mysqladmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8101:80"
    restart: always
    depends_on:
      - db
  rails:
    container_name: quote_rails
    build:
      context: .
      dockerfile: rails.Dockerfile
    environment:
      QUOTE_DATABASE_PASSWORD: quote_development      
    ports:
      - "8102:3000"
    depends_on:
      - db
    

