# docker-compose.yaml - compose five docker images to run zitat-service.de
# - mariadb with loaded test data
# - phpmysqladmin
# - rails web application
# - Selenium with headless chrome and VNC server for testing
# - maildev SMTP server for testing emails
version: '3.5'
services:
  db:
    container_name: quote_mariadb
    build:
      context: .
      dockerfile: db.Dockerfile
    image: mariadb
    volumes:
      - .:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quote_development
      MYSQL_USER: quote_development
      MYSQL_PASSWORD: quote_development
    ports:
      - "8100:3306"
    restart: always
  mysqladmin:
    container_name: quote_mysqladmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8101:80"
    restart: always
    depends_on:
      - db
  rails:
    container_name: quote_rails
    build:
      context: .
      dockerfile: rails.Dockerfile
    volumes:
      - .:/quote
    environment:
      QUOTE_DATABASE_PASSWORD: quote_development      
    ports:
      - "8102:3000"
      - "8103:3100"
    depends_on:
      - db
      - chrome
  chrome:
    container_name: quote_chrome
    image: selenium/standalone-chrome-debug
    ports:
      - "8104:5900"
    volumes:
      - /dev/shm:/dev/shm
  maildev:
    container_name: quote_maildev
    image: maildev/maildev
    ports:
      - "8105:80"
